### ISSUE TITLE
Check on transformation between directional and coordinate space 

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#1]
In the function `generate_samples` in `smpsite/smpsite/sampling.py`, I am converting the directions corresponding to secular variation from directional space to (inclination, declination). Then I add Fisher noise in this space. I want to check that the functions I am using from `pmagpy` are the right ones to do this transformation. 

```
    # sample secular variations
    # lat, lon
    # here is where I can replace by TK03 model
    secular_declinations, secular_inclinations = ipmag.fishrot(k=params.kappa_secular,
                                                               n=N_sites, 
                                                               dec=0, 
                                                               inc=90, 
                                                               di_block=False)
    
    for i, nk in enumerate(design):
        outliers = np.random.binomial(1, params.outlier_rate, nk)
        outliers = sorted(outliers)
        n_outliers = np.sum(outliers)
        n_samples = nk - n_outliers
        
        # Transform VGP coordinates to directions (D, I) coordinates 
        # inc, dec
        dec_vgp, inc_vgp = pmag.vgp_di(plat=secular_inclinations[i], 
                                       plong=secular_declinations[i], 
                                       slat=params.site_lat, 
                                       slong=params.site_long)

    
        # Sample real samples (within-site)
        declinations, inclinations = ipmag.fishrot(k=params.kappa_vgp, 
                                                   n=n_samples,
                                                   dec=dec_vgp,
                                                   inc=inc_vgp,
                                                   di_block=False)

        # Convert specimenst to geographical space
        for j in range(len(declinations)):
            trans_dec, trans_inc, _, _ = pmag.dia_vgp(declinations[j], inclinations[j], 0, params.site_lat, params.site_long)
            declinations[j] = trans_dec
            inclinations[j] = trans_inc
```

I would also like to include the TK03 sampling of the secular variations in the sampling, instead of sampling from Fisher with unknown kappa. 

On the other side, I wonder if I need to do the same at the moment of estimating the mean direction. That is, instead of taking averages of averages in coordinate space, should I compute the average of the site directions in the directional space, transform these to coordinate space and then compute the Fisher mean but in coordinate space? That is, the mean-site direction is computed in (inc, dec) space, while the mean of VGPs is computed in the (lat, lon) space? 

Thank you @LenGallo for the help! Feel free to do a Pull Request with changes or open issues if there is something that needs fix.

**Comment by LenGallo** [comment]
Hi @facusapienza21 , 

I have made some changes in the tk03 branch

For now, I changed the attributes of the class `class params()` so that we play with the latitude as the governing parameter of secular variation and we get rid of `kappa_secular`. Next step, we can jump to Model G which follows a straightforward functional relationship between the dispersion of vgps (note that this would live in the 'pole' space) and latitude. 

- I made some changes in the `generate_samples` function, it now returns a DF in the geographic\VGP\Pole space.

Still need to see how these changes merge or not with your subsequent workflow, but I am brain-dead now, I can keep working on this tomorrow.

Cheers,
Lean

**Comment by LenGallo** [comment]
Hi again @facusapienza21 ,

The sampling of directions from the statistical model of paleosecular TK03 is already implemented. Now, the dispersion of VGPs is governed by the latitude of the sampling site. Looking forward to seeing how you handle all these covariant parameters! The params class for the sampling strategy now has the following structure:

```
class Params(NamedTuple):
    
    kappa_within_site : float    
    site_lat : float # Governing parameter of the concentration
    outlier_rate : float
    N_per_site: int
    N : int    
    site_long : float
```

As for the averaging process: we know that VGPs conform to a Fisher distribution, so you should calculate the mean pole from `vgp_lat` and `vgp_lon`, as it is implemented now. 

As for the  MLE, I haven't dwelled too much on it, so it won't work (although it is just a matter of changing the names of the columns). I like it, although as it is implemented now, it does not take into account the uncertainties on the site_means. I made a couple of suggestions/comments in the code in this regard. Specifically, we could also add some additional information (e.g. kappa within-site, as calculated from `ipmag.Fisher()` or `csd`) and start playing with them.

abrazo,
lean

**Comment by facusapienza21** [comment]
@all-contributors please add @LenGallo for mentoring
