### ISSUE TITLE
Pmagpy in environment file

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#12]
When exporting a conda environment that has pmagpy installed inside, this doesn't show in the `environment.yml` file or in the listed dependencies with conda. I wonder if I should manually add at the end with the `pip` clause or is there is a better way of doing this. Maybe exporting the dependencies with pip? How do you usually do this @Swanson-Hysell @duserzym ?

**Comment by Swanson-Hysell** [comment]
I think manually adding with pip is the way to go. The other necessary packages should be in the environment.yml.

**Comment by Swanson-Hysell** [comment]
Has this worked?

**Comment by facusapienza21** [comment]
It does @Swanson-Hysell ! You can tested with the Binder link provided in the `README` and also you can create the environment from the `environment.yml` file or directly using the `Makefile` with `make env`.
