### ISSUE TITLE
Compute the error with outliers for the case with one sample per site and simple outlier test

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#18]
For Figure 3, it could be useful to also include in panel (c) the figure with the one sample per site case where we allow to have the very simple test of filtering points that are outside the 45 degree band around the previously estimated mean. 

This also open the question of how to estimate the mean in the more efficient way.

**Comment by LenGallo** [comment]
@facusapienza21 if it happens that you want to test one more outlier detection algorithm in the VGP level in order to have one more group in the nice boxplot, apart from Vandame cutoff, you can apply the 45° cutoff by simply adding in the `estimate_pole` below vandamme:

```
  # Filter VGPs based on Vandamme method
  if ignore_outliers == 'vandamme': 
      df_site, _, _ = pmag.dovandamme(df_site)

  # Filter VGPs based on 45° cutoff method
  if ignore_outliers == 'forty_five': 
      df_site =  df_site[df_site["vgp_lat"]>45]
```
