### ISSUE TITLE
crop x-axis (samples per site) on Figure 1 panels

### ISSUE THREAD

**Issue by Swanson-Hysell** [PolarWandering/PaleoSampling#21]
For both of these plots, it seems a bit silly to have the x-axis go all the way to 40. I don't know of any paleomagnetic study in the literature that has developed that many samples per site. Given that the improvement in number of sample per site asymptotes well before then, not much information is being communicated. Given that it is interested to see the asymptotic behavior, but to also see that there is improvement in the range of 1 to 5 having the x_max be 15 or 20 would be better.

**Comment by LenGallo** [comment]
I agree. Also, perhaps you could lengthen the y-axis (up to 60-80) and put both plots side by side. This will make the graphic more visually attractive (two standing rectangles) and also, the asymptote of 300 (a doable sampling campaign) would then go to n_0 = 1.

**Comment by Swanson-Hysell** [comment]
I don't think we should increase the y-axis it by too much. For example, in the current Nordic compilation of high quality paleomagnetic poles the 95th percentile number of sites is 52. So I wouldn't go above 60 (which could be preferable to the current 40).
