### ISSUE TITLE
incorporate calculation of S parameter into the process

### ISSUE THREAD

**Issue by Swanson-Hysell** [PolarWandering/PaleoSampling#4]
In addition to estimating $\mu$, we want to calculate the VGP scatter ($S$) as this is another parameter that paleomagnetists seek to determine. 

VGP scatter is quantified by the parameter $S_p$  (e.g., 1969), defined  as:

$$
S_p^2 = (N -1)^{-1} \sum_{i=1}^N (\Delta_i)^2
$$

where $N$ is the number of observations and $\Delta_i$ is the angle between the $i^{th}$ VGP and the spin axis.  

To address the issue of within site scatter,  some studies use a cutoff for $\kappa$ or $\alpha_{95}$ for inclusion in the calculation, while others adjust the value of $S_p$ to account for the within site scatter $S_w$.   

McElhinny and McFadden (1997) defined a parameter $S_f$:

$$
S_f^2 = S_p^2 - (S_w^2/\bar n),
$$

where  $\bar n$ is the average number of samples per site.

The VGP scatter is calculated in https://github.com/PmagPy/PmagPy/blob/master/pmagpy/ipmag.py with the function ```sb_vgp_calc```. This function is currently setup to accept a data frame — which should be generalized. It has a parameter for whether to not to do within site scatter correction.

**Comment by facusapienza21** [comment]
This has been included in the manuscript and it will be incorporated in the code soon.

**Comment by facusapienza21** [comment]
@all-contributors please add @Swanson-Hysell for ideas
