### ISSUE TITLE
Standardize notation in all code

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#5]
Change all notation in the code to be consistent with the manuscript and the standard notation

- `N_sites`: Total number of sites.
- `n_samples_site`: Total number of samples per site.
- `n_samples`: Total number of samples. This should be equal to `N_sites * n_samples_site`.  

We can also use 
- `kappa_insite`: Kappa of the Fisher distribution for sampling within site. 
- `outlier_rate`: Proportion of expected outliers. 
- `latitude`, `longitude`: These correspond to the paleo-latitudes/longitudes used for going from (dec, inc) to (lat, lon).

**Comment by Swanson-Hysell** [comment]
I added this comment in Overleaf, but can reiterate it here. I think that using `p` for outlier rate in the main text is confusing. There is enough for the reader to try to keep track of without this notation (which I find non-intuitive). That choice of notation becomes particularly confusing when it I presented that `p=0.05` associated with one of the outlier rate simulations. I realize it isn't succinct, but perhaps we just go with `outlier_rate`?

**Comment by facusapienza21** [comment]
I agree with this @Swanson-Hysell . I will think about a better name for the outlier rate, but I agree that `p` may be misleading, and keeping the notation more explicit may help. What about `p_{outlier}`? So we keep the `p` for probability?

**Comment by Swanson-Hysell** [comment]
That notation could work well.
