### ISSUE TITLE
Figure 2 for different algorithms performace

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#6]
For the second figure in the paper, we want to understand how the Mean Square Error dispersion from the true pole compares when we use 
1. Lower number of samples per site (=1) without outlier detection algorithm
2. High number of samples per site (=5) with a perfect outlier detection algorithm 
In the case where the total number of samples is kept fixed. I was thinking of something like 1x50 vs 5x10 for this.

We are going to compare these two methods when we vary i) the dispersion parameter kappa per site (from 10 to 1000, logscale) and ii) the latitude (from 0 to 90). Here we want to compare the difference between MSE between 1 and 2 as we move i and ii, possibly in a colormap 2d plot.  

Thoughts on this @LenGallo @Swanson-Hysell @duserzym @matdomeier @bramvaes?

**Comment by facusapienza21** [comment]
Hi @LenGallo @Swanson-Hysell @matdomeier @duserzym @bramvaes 

I ran some simulations for a second figure comparing the difference in performance for estimating the pole for the following two scenarios
- **Method 1**: 50 samples total, with 10 sites, 5 samples per site, and perfect outlier detection algorithms
- **Method 2**: 50 samples total, with 50 sites, 1 sample per site, no outlier detection algorithm
 
I did this for the following other values
- paleolatitude (important for the tk03 sampling) between 0 and 90, 10 degrees step
- kappa in-site between 10 and 1000, logscale
- outlier rate = 0.0, 0.05, 0.10, 0.20

All the results show that Method 2 is always better. The next plot is for 20% outliers, and still Method 2 has better. The color represents the overall percentual improvement of method 2 over 1, that is (MSE_1 - MSE_2) / MSE_1, with MSE the mean square error of each method (small MSE is better). 

<img width="596" alt="Screen Shot 2023-02-26 at 9 47 53 PM" src="https://user-images.githubusercontent.com/39526081/221484453-59907d97-9f6f-4f45-861a-58afc3bbb7cd.png">

And here for 10% outliers. You can run this code from the notebook `Figure2.ipynb` inside the folder `figures`. 

<img width="597" alt="Screen Shot 2023-02-26 at 9 53 56 PM" src="https://user-images.githubusercontent.com/39526081/221485357-129f8804-6213-402f-8767-6f1ac90055bd.png">

In all cases, the plot is fully blue, ie, Method 2 is better. I would like to see where Method 1 starts being better. For that, on option is to increase even more (> 20%) the proportion of outliers of change the total number of samples to something lower that 50. What do you think? This simulations take some time to run and I am still working in making the sampling faster (see #9). 

Also: do you know that happens with tk03 when latitude = 90? The results I got in that case make no sense in comparision with the rest of the latitudes.

**Comment by Swanson-Hysell** [comment]
I think it is quite important to show the distributions coming out of simulations such as this. When we were looking at it together, these distributions were quite informative. When doing a study or assessing a result, we are quite interested in how confident we can be in that result. It is one thing for that approach to be better on average, but if it increases the probability of being quite wrong some of the time, it is more complicated to say it is "better."

Regarding 
> Also: do you know that happens with tk03 when latitude = 90?

It is effectively impossible to be at latitude = 90 as it is a singularity, so I wouldn't worry about it too much. Does 89º work?

**Comment by matdomeier** [comment]
Hi Facu,


Very interesting. From my perspective, it would be more valuable to see when method 1 might 'prevail' by further increasing the outlier rate rather than decreasing the sample number below 50 (although both would be interesting). This is because it isn't common for people to collect less than 50 samples for a given study these days, but it isn't unheard of to have a success rate of much less than 80%.


Cheers,

-Mat

________________________________

**Comment by facusapienza21** [comment]
Following on @Swanson-Hysell and @matdomeier comments plus my discussion today with @bramvaes I think the next thing I will do for this plot is to create a similar illustration but where the color represents what is the proportion of outliers you need to have in order to make one or the other method to work better in average. As we can see for this plot, I expect that value to be above 20% for most of the cases. Following on @Swanson-Hysell comment, I was planning to add another companion plot where we see the full distribution of errors (instead of just the mean performance) and we can also evaluate the coverage percentage of the alpha95 band, so you can obtain both information from the plots.

**Comment by facusapienza21** [comment]
Also for this, as @bramvaes mentioned we can test how these results change when we use a very simple outlier detection algorithm for the few samples per sita case where we exclude vgps outside a 45 degree dispersion of the estimated mean. This is something we can always do and I think is common practice and will definitively make the comparison more fair.

**Comment by facusapienza21** [comment]
@all-contributors please add @matdomeier for ideas design
