### ISSUE TITLE
Optimize Sampling/Estimation time of code

### ISSUE THREAD

**Issue by facusapienza21** [PolarWandering/PaleoSampling#9]
Right now, a bottleneck of all the simulations is the required time. A profiling of the code should be executed to see what is consuming all the execution time. A quick scan revealed that the problem doesn't seem to be coming from the sampling or mean estimation per se, so there must be some other operation in the code that is time-consuming and probably can be replaced. 

More exploration is needed.

**Comment by LenGallo** [comment]
@facusapienza21 is this running already in parallel? I can take that in the short/mid term otherwise

**Comment by facusapienza21** [comment]
@LenGallo this is currently running in parallel. The problem with the total running time cames from the time required to sample Fisher and TK03. Here a short demo:

- **tk03 sampling**: 180 +- 20 ms clock time.
```
%%timeit
_ = ipmag.tk03(n=100, dec=0, lat=20, rev='no', G1=-18e3, G2=0, G3=0, B_threshold=0);
```

- **Fisher sampling**: 32 +- 9 ms clock time.
```
%%timeit
_ = ipmag.fishrot(k=40, n=100, dec=0, inc=0, di_block=False);
``` 
I do think we can do this more efficiently, since the current numpy samplers are much faster, by three orders of magnitude.
 - **Multivariate Gaussian**:  18 +- 3 **microseconds**
```
%%timeit
_ = np.random.normal(size=(3,100));
```

I think the samplers for the fisher and tk03 can be improved to run this fast. For the Fisher, there are ways of sampling Fisher directly from gaussian, which will make the fisher sampler run at the same order of magnitude than the gaussian sampler. 

Another solution is to generate a large sample from tk03 and Fisher (~10000) with given paleolatitude and dispersion, saved it in memory and then subsample from this to generate high resolution plots as we move n and N in the simulations. This is not going to change the final result, but it's not the most elegant solution. 

Maybe we can take a look to the implementation of the Fisher / TK03 sampler? @Swanson-Hysell @LenGallo ?

**Comment by facusapienza21** [comment]
Ok, I follow a rabbit hole here but I think I discovered a way of doing the Fisher sampling faster. 

The sampling of the Fisher distribution is done collectively by `pmag.fshdev()` and `ipymag.fishrot()`. Both functions had being desing to make more than one sample, but right now that feature is not exploted and the sampling of the Fisher samples is done one by one using `np.random` instead of one single call to `np.random` with a generation of all the samples at once. Here a demostrations. 

These are the original funcions: 
```
import numpy as np
from numpy import random
import pmagpy.pmag as pmag

def fshdev(k):
    """
    Generate a random draw from a Fisher distribution with mean declination
    of 0 and inclination of 90 with a specified kappa.
    Parameters
    ----------
    k : single number or an array of values
        kappa (precision parameter) of the distribution
    Returns
    -------
    dec, inc : declination and inclination of random Fisher distribution draw
               if k is an array, dec, inc are returned as arrays, otherwise, single values
    
    Examples
    --------
    >>> pmag.fshdev(8)
    (334.3434290469283, 61.06963783415771)
    """
    k = np.array(k)
    if len(k.shape) != 0:
        n = k.shape[0]
    else:
        n = 1
    R1 = random.random(size=n)
    R2 = random.random(size=n)
    L = np.exp(-2 * k)
    a = R1 * (1 - L) + L
    fac = np.sqrt(-np.log(a)/(2 * k))
    inc = 90. - np.degrees(2 * np.arcsin(fac))
    dec = np.degrees(2 * np.pi * R2)
    if n == 1:
        return dec[0], inc[0]  # preserve backward compatibility
    else:
        return dec, inc
    
def fishrot(k=20, n=100, dec=0, inc=90, di_block=True):
    """
    Generates Fisher distributed unit vectors from a specified distribution
    using the pmag.py function pmag.fshdev() and pmag.dodirot() functions.
    Parameters:
        k : kappa precision parameter (default is 20)
        n : number of vectors to determine (default is 100)
        dec : mean declination of distribution (default is 0)
        inc : mean inclination of distribution (default is 90)
        di_block : this function returns a nested list of [dec,inc,1.0] as the default
        if di_block = False it will return a list of dec and a list of inc
    Returns:
        - di_block, a nested list of [dec,inc,1.0] (default)
        - dec, inc, a list of dec and a list of inc (if di_block = False)
    Examples:
        >>> ipmag.fishrot(k=20, n=5, dec=40, inc=60)
        [[44.766285502555775, 37.440866867657235, 1.0],
        [33.866315796883725, 64.732532250463436, 1.0],
        [47.002912770597163, 54.317853800896977, 1.0],
        [36.762165614432547, 56.857240672884252, 1.0],
        [71.43950604474395, 59.825830945715431, 1.0]]
    """
    directions = []
    declinations = []
    inclinations = []
    if di_block == True:
        for data in range(n):
            d, i = fshdev(k)
            drot, irot = pmag.dodirot(d, i, dec, inc)
            directions.append([drot, irot, 1.])
        return directions
    else:
        for data in range(n):
            d, i = fshdev(k)
            drot, irot = pmag.dodirot(d, i, dec, inc)
            declinations.append(drot)
            inclinations.append(irot)
        return declinations, inclinations
``` 

We can see there are two for loops nested in `fishrot()`. I rewrite this funciton to make one single call to the random generator funcion and make the rotation of all the directions at once: 
```
def fishrot_fast(k=20, n=100, dec=0, inc=90, di_block=True):
    """
    Generates Fisher distributed unit vectors from a specified distribution
    using the pmag.py function pmag.fshdev() and pmag.dodirot() functions.
    Parameters:
        k : kappa precision parameter (default is 20)
        n : number of vectors to determine (default is 100)
        dec : mean declination of distribution (default is 0)
        inc : mean inclination of distribution (default is 90)
        di_block : this function returns a nested list of [dec,inc,1.0] as the default
        if di_block = False it will return a list of dec and a list of inc
    Returns:
        - di_block, a nested list of [dec,inc,1.0] (default)
        - dec, inc, a list of dec and a list of inc (if di_block = False)
    Examples:
        >>> ipmag.fishrot(k=20, n=5, dec=40, inc=60)
        [[44.766285502555775, 37.440866867657235, 1.0],
        [33.866315796883725, 64.732532250463436, 1.0],
        [47.002912770597163, 54.317853800896977, 1.0],
        [36.762165614432547, 56.857240672884252, 1.0],
        [71.43950604474395, 59.825830945715431, 1.0]]
    """
    directions = []
    declinations = []
    inclinations = []
    if di_block == True:
        declinations, inclinations = fshdev(np.repeat(k, n))
        Block = np.array([declinations, inclinations, np.repeat(1, n)]).T
        res = pmag.dodirot_V(Block, np.repeat(dec, n), np.repeat(inc, n))
        # for data in range(n):
        #     d, i = fshdev(k)
        #     drot, irot = pmag.dodirot(d, i, dec, inc)
        #     directions.append([drot, irot, 1.])
        # return directions
        return res[:,0], res[:,1]
    else:
        for data in range(n):
            d, i = fshdev(k)
            drot, irot = pmag.dodirot(d, i, dec, inc)
            declinations.append(drot)
            inclinations.append(irot)
        return declinations, inclinations
```

With this new implementation, we observe a significant improvement of the sampling: 
- Original Fisher sampling implementation: **34.7 +- 7.27 ms**
```
%%timeit
res_slow = fishrot(n=100, k=20);
```
- New implementation: **350 +- 77 microsec**
```
%%timeit
res_fast = fishrot_fast(n=100, k=20);
```

I will probably use this sampling for the simulations, but I wonder if it makes sense to make a PR to Pmagpy with this in the future. @Swanson-Hysell ?

**Comment by Swanson-Hysell** [comment]
Nice to get a two order of magnitude speed up! This should help matters.

Yes. Putting in a pull request to PmagPy makes sense.

It looks like it would be good to pull the generation of the samples out of the `if di_block == True:` if/else statement. The samples can be pulled in this more efficient way and then they can either be returned as the nested list or the declinations, inclinations list.

Can we change the name of the internal `Block` array to be something more informative. Say `resampled_di` and we could have `res` be `resampled_di_rotated`?
